
Primer3 File - http://primer3.sourceforge.net

P3_FILE_TYPE=settings

P3_FILE_ID=Default settings of primer3 version 1.1.4

<input name="PRIMER_TASK" value="pick_detection_primers">
<input name="PRIMER_PICK_LEFT_PRIMER" value="1">
<input name="PRIMER_PICK_INTERNAL_OLIGO" value="0">
<input name="PRIMER_PICK_RIGHT_PRIMER" value="1">
<input name="PRIMER_NUM_RETURN" value="5">
<input name="PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION" value="5">
<input name="PRIMER_PRODUCT_SIZE_RANGE" value="100-300">
<input name="PRIMER_PRODUCT_OPT_SIZE" value="0">
<input name="PRIMER_PAIR_WT_PRODUCT_SIZE_LT" value="0.0">
<input name="PRIMER_PAIR_WT_PRODUCT_SIZE_GT" value="0.0">
<input name="PRIMER_MIN_SIZE" value="18">
<input name="PRIMER_INTERNAL_MIN_SIZE" value="18">
<input name="PRIMER_OPT_SIZE" value="20">
<input name="PRIMER_INTERNAL_OPT_SIZE" value="20">
<input name="PRIMER_MAX_SIZE" value="27">
<input name="PRIMER_INTERNAL_MAX_SIZE" value="27">
<input name="PRIMER_WT_SIZE_LT" value="1.0">
<input name="PRIMER_INTERNAL_WT_SIZE_LT" value="1.0">
<input name="PRIMER_WT_SIZE_GT" value="1.0">
<input name="PRIMER_INTERNAL_WT_SIZE_GT" value="1.0">
<input name="PRIMER_MIN_GC" value="20.0">
<input name="PRIMER_INTERNAL_MIN_GC" value="20.0">
<input name="PRIMER_OPT_GC_PERCENT" value="50.0">
<input name="PRIMER_MAX_GC" value="80.0">
<input name="PRIMER_INTERNAL_MAX_GC" value="80.0">
<input name="PRIMER_WT_GC_PERCENT_LT" value="0.0">
<input name="PRIMER_INTERNAL_WT_GC_PERCENT_LT" value="0.0">
<input name="PRIMER_WT_GC_PERCENT_GT" value="0.0">
<input name="PRIMER_INTERNAL_WT_GC_PERCENT_GT" value="0.0">
<input name="PRIMER_GC_CLAMP" value="0">
<input name="PRIMER_MAX_END_GC" value="5">
<input name="PRIMER_MIN_TM" value="57.0">
<input name="PRIMER_INTERNAL_MIN_TM" value="57.0">
<input name="PRIMER_OPT_TM" value="60.0">
<input name="PRIMER_INTERNAL_OPT_TM" value="60.0">
<input name="PRIMER_MAX_TM" value="63.0">
<input name="PRIMER_INTERNAL_MAX_TM" value="63.0">
<input name="PRIMER_PAIR_MAX_DIFF_TM" value="100.0">
<input name="PRIMER_WT_TM_LT" value="1.0">
<input name="PRIMER_INTERNAL_WT_TM_LT" value="1.0">
<input name="PRIMER_WT_TM_GT" value="1.0">
<input name="PRIMER_INTERNAL_WT_TM_GT" value="1.0">
<input name="PRIMER_PAIR_WT_DIFF_TM" value="0.0">
<input name="PRIMER_PRODUCT_MIN_TM" value="-1000000.0">
<input name="PRIMER_PRODUCT_OPT_TM" value="0.0">
<input name="PRIMER_PRODUCT_MAX_TM" value="1000000.0">
<input name="PRIMER_PAIR_WT_PRODUCT_TM_LT" value="0.0">
<input name="PRIMER_PAIR_WT_PRODUCT_TM_GT" value="0.0">
<input name="PRIMER_TM_FORMULA" value="0">
<input name="PRIMER_SALT_MONOVALENT" value="50.0">
<input name="PRIMER_INTERNAL_SALT_MONOVALENT" value="50.0">
<input name="PRIMER_SALT_DIVALENT" value="0.0">
<input name="PRIMER_INTERNAL_SALT_DIVALENT" value="0.0">
<input name="PRIMER_DNTP_CONC" value="0.0">
<input name="PRIMER_INTERNAL_DNTP_CONC" value="0.0">
<input name="PRIMER_SALT_CORRECTIONS" value="0">
<input name="PRIMER_DNA_CONC" value="50.0">
<input name="PRIMER_INTERNAL_DNA_CONC" value="50.0">
<input name="PRIMER_MAX_SELF_ANY" value="8.00">
<input name="PRIMER_INTERNAL_MAX_SELF_ANY" value="12.00">
<input name="PRIMER_PAIR_MAX_COMPL_ANY" value="8.00">
<input name="PRIMER_WT_SELF_ANY" value="0.0">
<input name="PRIMER_INTERNAL_WT_SELF_ANY" value="0.0">
<input name="PRIMER_PAIR_WT_COMPL_ANY" value="0.0">
<input name="PRIMER_MAX_SELF_END" value="3.00">
<input name="PRIMER_INTERNAL_MAX_SELF_END" value="12.00">
<input name="PRIMER_PAIR_MAX_COMPL_END" value="3.00">
<input name="PRIMER_WT_SELF_END" value="0.0">
<input name="PRIMER_INTERNAL_WT_SELF_END" value="0.0">
<input name="PRIMER_PAIR_WT_COMPL_END" value="0.0">
<input name="PRIMER_MAX_END_STABILITY" value="100.0">
<input name="PRIMER_WT_END_STABILITY" value="0.0">
<input name="PRIMER_MAX_NS_ACCEPTED" value="0">
<input name="PRIMER_INTERNAL_MAX_NS_ACCEPTED" value="0">
<input name="PRIMER_WT_NUM_NS" value="0.0">
<input name="PRIMER_INTERNAL_WT_NUM_NS" value="0.0">
<input name="PRIMER_MAX_POLY_X" value="5">
<input name="PRIMER_INTERNAL_MAX_POLY_X" value="5">
<input name="PRIMER_MIN_THREE_PRIME_DISTANCE" value="-1">
<input name="PRIMER_PICK_ANYWAY" value="0">
<input name="PRIMER_LOWERCASE_MASKING" value="0">
<input name="PRIMER_EXPLAIN_FLAG" value="0">
<input name="PRIMER_LIBERAL_BASE" value="0">
<input name="PRIMER_FIRST_BASE_INDEX" value="0">
<input name="PRIMER_MAX_TEMPLATE_MISPRIMING" value="-1.00">
<input name="PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING" value="-1.00">
<input name="PRIMER_WT_TEMPLATE_MISPRIMING" value="0.0">
<input name="PRIMER_PAIR_WT_TEMPLATE_MISPRIMING" value="0.0">
<input name="PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS" value="1">
<input name="PRIMER_MAX_LIBRARY_MISPRIMING" value="12.00">
<input name="PRIMER_INTERNAL_MAX_LIBRARY_MISHYB" value="12.00">
<input name="PRIMER_PAIR_MAX_LIBRARY_MISPRIMING" value="24.00">
<input name="PRIMER_WT_LIBRARY_MISPRIMING" value="0.0">
<input name="PRIMER_INTERNAL_WT_LIBRARY_MISHYB" value="0.0">
<input name="PRIMER_PAIR_WT_LIBRARY_MISPRIMING" value="0.0">
<input name="PRIMER_MIN_QUALITY" value="0">
<input name="PRIMER_INTERNAL_MIN_QUALITY" value="0">
<input name="PRIMER_MIN_END_QUALITY" value="0">
<input name="PRIMER_QUALITY_RANGE_MIN" value="0">
<input name="PRIMER_QUALITY_RANGE_MAX" value="100">
<input name="PRIMER_WT_SEQ_QUAL" value="0.0">
<input name="PRIMER_INTERNAL_WT_SEQ_QUAL" value="0.0">
<input name="PRIMER_PAIR_WT_PR_PENALTY" value="1.0">
<input name="PRIMER_PAIR_WT_IO_PENALTY" value="0.0">
<input name="PRIMER_INSIDE_PENALTY" value="-1.0">
<input name="PRIMER_OUTSIDE_PENALTY" value="0.0">
<input name="PRIMER_WT_POS_PENALTY" value="1.0">
<input name="PRIMER_SEQUENCING_LEAD" value="50">
<input name="PRIMER_SEQUENCING_SPACING" value="500">
<input name="PRIMER_SEQUENCING_INTERVAL" value="250">
<input name="PRIMER_SEQUENCING_ACCURACY" value="20">
<input name="PRIMER_WT_END_QUAL" value="0.0">
<input name="PRIMER_INTERNAL_WT_END_QUAL" value="0.0">
